w = float(input("Enter conductor weight per unit length (N/m): "))
L = float(input("Enter span length (m): "))
T = float(input("Enter conductor tension (N): "))
sag = (w * https://www.onlinegdb.com/#editor_1L**2) / (8 * T)
print("\n--- Result ---")
print(f"Span Length : {L:.2f} m")
print(f"Conductor Weight : {w:.2f} N/m")
print(f"Conductor Tension : {T:.2f} N")
print(f"Sag : {sag:.3f} m")
